[project]
name = "ModelStash"
authors = [{name = "BytePengwin"}]
version = "0.1.0"
description = "Simple container/invoker for llm models"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]
